//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainMonitor_.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class web_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal web_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainMonitor_.Views.Shared.web_Resources", typeof(web_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add District.
        /// </summary>
        public static string add_district {
            get {
                return ResourceManager.GetString("add_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Driver.
        /// </summary>
        public static string add_driver {
            get {
                return ResourceManager.GetString("add_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Railway.
        /// </summary>
        public static string add_railway {
            get {
                return ResourceManager.GetString("add_railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Station.
        /// </summary>
        public static string add_station {
            get {
                return ResourceManager.GetString("add_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Train.
        /// </summary>
        public static string add_train {
            get {
                return ResourceManager.GetString("add_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destrict  Management.
        /// </summary>
        public static string destrict_m {
            get {
                return ResourceManager.GetString("destrict_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Management.
        /// </summary>
        public static string driver_m {
            get {
                return ResourceManager.GetString("driver_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Reserved  Egypt Railway.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id_of_district {
            get {
                return ResourceManager.GetString("id_of_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id_of_station {
            get {
                return ResourceManager.GetString("id_of_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        public static string name_of_district {
            get {
                return ResourceManager.GetString("name_of_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name_of_station {
            get {
                return ResourceManager.GetString("name_of_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string notfcn {
            get {
                return ResourceManager.GetString("notfcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railway Management.
        /// </summary>
        public static string railway_m {
            get {
                return ResourceManager.GetString("railway_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string selectLang {
            get {
                return ResourceManager.GetString("selectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Management.
        /// </summary>
        public static string station_m {
            get {
                return ResourceManager.GetString("station_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-left.
        /// </summary>
        public static string t_dir {
            get {
                return ResourceManager.GetString("t_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Id.
        /// </summary>
        public static string t_id {
            get {
                return ResourceManager.GetString("t_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string t_loc {
            get {
                return ResourceManager.GetString("t_loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Map.
        /// </summary>
        public static string t_map {
            get {
                return ResourceManager.GetString("t_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Speed.
        /// </summary>
        public static string t_speed {
            get {
                return ResourceManager.GetString("t_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Management.
        /// </summary>
        public static string train_m {
            get {
                return ResourceManager.GetString("train_m", resourceCulture);
            }
        }
    }
}
